HW_Artemiy's_tasks_#3.2_StreamApi
vklda/JIS7 pull request #15
Opened 2021-05-27 17:36 UTC by vklda

2021-05-28 12:17 UTC, KaydunovDenis requested changes

2021-05-28 12:17 UTC, KaydunovDenis commented on src/main/java/homework/streamapi/task3_2/model/Product.java
> +    Integer discount;
- [ ] I think the fields should be private.

2021-05-28 12:17 UTC, KaydunovDenis commented on src/main/java/homework/streamapi/task3_2/App.java
> +
empty lines

2021-06-05 06:12 UTC, ArtikTico reviewed
Чекай комменты. Само решение норм. Исправь недочеты

2021-06-05 06:12 UTC, ArtikTico commented on src/main/java/homework/streamapi/task3_2/model/Product.java
> +    Integer discount;
Согласен. Добавь модификатор private.

2021-06-05 06:12 UTC, ArtikTico commented on src/main/java/homework/streamapi/task3_2/service/Service.java
> +    private Service() {
Зачем теб  конструктор для Service класса?

2021-06-12 18:30 UTC, ArtikTico approved these changes
Good job

2021-06-12 18:30 UTC, merged