HW_Artemiy's_tasks_#5_StreamApi
vklda/JIS7 pull request #16
Opened 2021-05-27 21:17 UTC by vklda

2021-05-28 12:03 UTC, KaydunovDenis requested changes
See my comments

2021-05-28 12:03 UTC, KaydunovDenis commented on src/main/java/homework/streamapi/task5/App.java
> +        userList.add(
On java11 you can use next the conctruction:
new ArrayList{{
add(user1);
add(user2;
//...etc
}}

2021-05-28 12:03 UTC, KaydunovDenis commented on src/main/java/homework/streamapi/task5/model/UserStatus.java
> +    private final String userType;
Не уверен, но если не расписывать
GUEST("GUEST"), а оставить просто GUEST, то разницы в твоем случае не будет
поэтому переменная userType лишняя.

2021-06-05 06:09 UTC, ArtikTico reviewed
Чекай комменты, а так все норм. Молодец

2021-06-05 06:09 UTC, ArtikTico commented on src/main/java/homework/streamapi/task5/service/Service.java
> +    private static boolean isGuest(User it) {
(User it) в методах так не пиши. User user лучше.

2021-06-05 06:09 UTC, ArtikTico commented on src/main/java/homework/streamapi/task5/service/Service.java
> +    private static boolean isActiveUser(User it) {
Смотри выше

2021-06-05 06:09 UTC, ArtikTico commented on src/main/java/homework/streamapi/task5/service/Service.java
> +    private static void deactivateIfNonAdult(User it) {
Тож самое

2021-06-05 06:09 UTC, ArtikTico commented on src/main/java/homework/streamapi/task5/service/Service.java
> +public class Service {
UserService, из названия Service не понятно для кого он пока не взглянешь на методы

2021-06-05 06:09 UTC, ArtikTico commented on src/main/java/homework/streamapi/task5/service/Service.java
> +    public static void setBetterUserStatusForGuestsAndActiveUsers(List<User> userList) {
`setBetterUserStatusForGuestsAndActiveUsers` -> `increaseUserStatus` остальное , а именно для какого типа пользователей ты повышаешь статус видно по коду

2021-06-12 18:32 UTC, ArtikTico approved these changes
good joob

2021-06-12 18:33 UTC, merged